### ISSUE TITLE
test_executability fails

### ISSUE THREAD

**Issue by arturo182** [Mr-Bossman/pi-pico2-linux#1]
I'm trying to get the setup running, my PSRAM seems to initialize correctly and I have tested it previously with CircuitPython, but https://github.com/Mr-Bossman/pi-pico2-linux/blob/master/psram-bootloader/src/bootloader.c#L187 results in a HardFault, any advice on what I could look into to get it working?

PS. GPIO0 is a valid XIP_CS and https://github.com/Mr-Bossman/pi-pico2-linux/blob/master/psram-bootloader/src/bootloader.c#L274 is stopping it from being accepted :grin:

**Comment by Mr-Bossman** [comment]
Oh, sorry, I missed this. We'll nice to know my check executableity function works correctly. Do u have a screenshot of the output. And what board are you using. Speaking of which, I should probably add one to the readme.

**Comment by arturo182** [comment]
Im afk right now so don't have the output, but I had the same result (HardFault as seen in gdb) on https://shop.pimoroni.com/products/Pimoroni-Pico-plus-2, https://ilabs.se/product/challenger-rp2350-wifi-ble/, and https://www.lectronz.com/products/rp2350-stamp-xl

**Comment by Mr-Bossman** [comment]
the https://ilabs.se/product/challenger-rp2350-wifi-ble has the same psram chip the other ones dont. so it should be as ez as changing `SFE_RP2350_XIP_CSI_PIN` to `0`

**Comment by arturo182** [comment]
Both the Sparkfun Pro Micro and the Pimoroni Pico Plus 2 use the APS6404L, but the Pimoroni one is in a smaller package. On the Stamp, I use an ESP-PSRAM64, so that is different. The only change for Pimoroni and iLabs was to adjust the PSRAM pin.

Here is a screenshot of the serial and gdb output when running on the Pimoroni Pico Plus 2 (same result as the iLabs):

**Comment by Mr-Bossman** [comment]
> Both the Sparkfun Pro Micro and the Pimoroni Pico Plus 2 use the APS6404L, but the Pimoroni one is in a smaller package.

Ah ok.

> On the Stamp, I use an ESP-PSRAM64, so that is different. The only change for Pimoroni and iLabs was to adjust the PSRAM pin.

It seems like writing to the ram is working, as in R/W, but it isn't executing. I'm assuming you have changed the board here https://github.com/Mr-Bossman/pi-pico2-linux/blob/master/psram-bootloader/CMakeLists.txt#L37. I honestly have no clue why it doesn't work, I would just play around with it. I'm on vacation with my friends so cant be of help for the next few days, though here is what the output is supposed to look like.

![image](https://github.com/user-attachments/assets/3cbb87e1-fb23-4b95-af0c-20d9b11344c3)

**Comment by arturo182** [comment]
No worries, enjoy your vacation and write back whenever you have time. You did amazing work on the port already! Thanks for trying to help me, I'll try to poke some things and see if I can figure it out :)

**Comment by arturo182** [comment]
Here's a dump of all the registers:

```
(gdb) info registers 
r0             0x1d                29
r1             0x200019b0          536877488
r2             0x0                 0
r3             0x8082              32898
r4             0x117ffffc          293601276
r5             0x2000199c          536877468
r6             0x8082              32898
r7             0x400e0014          1074659348
r8             0x43280035          1126694965
r9             0x0                 0
r10            0x10000000          268435456
r11            0x62707361          1651536737
r12            0xff                255
sp             0x20081fc8          0x20081fc8
lr             0xfffffff9          -7
pc             0x10000114          0x10000114 <isr_hardfault>
xpsr           0x69000003          1761607683
fpscr          0x0                 0
msp            0x20081fc8          0x20081fc8
psp            0x0                 0x0
msp_ns         0x0                 0x0
psp_ns         0xfffffffc          0xfffffffc
msp_s          0x20081fc8          0x20081fc8
psp_s          0x0                 0x0
primask        0x0                 0
basepri        0x0                 0
faultmask      0x0                 0
control        0x0                 0
msplim_s       0x0                 0x0
psplim_s       0x0                 0x0
msplim_ns      0x0                 0x0
psplim_ns      0x0                 0x0
primask_s      0x0                 0
basepri_s      0x0                 0
faultmask_s    0x0                 0
control_s      0x0                 0
primask_ns     0x0                 0
basepri_ns     0x0                 0
faultmask_ns   0x0                 0
control_ns     0x0                 0
```

Reading the UsageFault Status Register (UFSR), we get 0x2 = `INVSTATE`
```
(gdb) print/x *(uint16_t *)0xE000ED2A
$1 = 0x2
```

Which according to https://interrupt.memfault.com/blog/cortex-m-hardfault-debug#ufsr means 

> INVSTATE - Indicates the processor has tried to execute an instruction with an invalid Execution Program Status Register (EPSR) value. Among other things the ESPR tracks whether or not the processor is in thumb mode state. Instructions which use “interworking addresses”[2](https://interrupt.memfault.com/blog/cortex-m-hardfault-debug#fn:1) (bx & blx or ldr & ldm when loading a pc-relative value) must set bit[0] of the instruction to 1 as this is used to update ESPR.T. If this rule is violated, a INVSTATE exception will be generated. When writing C code, the compiler will take care of this automatically, but this is a common bug which can arise when hand-writing assembly.

This is a bit above my knowledge level :sweat_smile: 

I was wondering if maybe we have different compiler versions so the state of the registers is different when that code is attempted to be executed, I tried rebuilding with `set(PICO_DEOPTIMIZED_DEBUG ON)` so that `-O0` is used, but still, same result.

**Comment by Mr-Bossman** [comment]
Oh, I should have caught this earlier since your gdb was armed, but I assumed it was multiarch or something. Anyway, this only works on the riscv core right now, though it should be trial to get it running on arm. Can you recompile using the riscv core.

**Comment by arturo182** [comment]
One detail I noticed (probably not related, but worth noting) is that in your screenshot the partition is 4M, but in the checked in json, it's 8M: https://github.com/Mr-Bossman/pi-pico2-linux/blob/master/psram-bootloader/partition_table.json#L18

When I tried and changed ti to 4M, flashing the kernel fails because it is too large for 4M.

```bash
> picotool load -fxp 0 ../buildroot/output/images/flash-image.bin
Downloading into partition 0:
  00010000->00410000
ERROR: File size 0x600000 is too big to fit in partition size 0x400000

```

**Comment by Mr-Bossman** [comment]
The partition size is unrelated. It was just because I didn't have a root fs in that screenshot

**Comment by arturo182** [comment]
> Oh, I should have caught this earlier since your gdb was armed, but I assumed it was multiarch or something. Anyway, this only works on the riscv core right now, though it should be trival to get it running on arm. Can you recompile using the riscv core.

Oh this would explain a lot, it's because I am compiling from command line and this whole block was making a lot of assumptions so I deleted it, but I didn't realize that it was also setting the PLATFORM to riscv! https://github.com/Mr-Bossman/pi-pico2-linux/blob/master/psram-bootloader/CMakeLists.txt#L12

Building the toolchain now, will report back, but it seems likely this is the cause.

Sorry for my oversight!

**Comment by arturo182** [comment]
Yes, that was the issue, do I feel silly 😅 Sorry for wasting your time, and on your vacation!

Now I get the kernel booting to a point but erroring eventually 🤔

**Comment by Mr-Bossman** [comment]
Yes, it runs out of memory, unfortunately. I haven't gotten a shell working.... you can get the kernel to fit in ~2.3Mb by disabling a bunch of stuff in the config. Then it starts sh, but then the shell runs out of memory, too.

**Comment by arturo182** [comment]
Well, I did use it, it's just that your cmake file expects the sdk and toolchain to be in a specific location and I don't use the vscode extension so I have them checked out in another place.

**Comment by Mr-Bossman** [comment]
Lol I just used the extension to install the SDK to a standard location
hopeing for this exact thing not to happen. Anyway it's fine.
Would be nice to know how to change the sdk and tools location though.

**Comment by arturo182** [comment]
The cmake file should probably check if `PICO_SDK_PATH` is set in the env and only set it to the default location if not already defined.

I've been trying to disable as many options and lower as many values in the kernel as possible, but no shell so far 😅

**Comment by Mr-Bossman** [comment]
> The cmake file should probably check if `PICO_SDK_PATH` is set in the env and only set it to the default location if not already defined.

It seems like the vscode extension is a bit broken and overwrites them. i updated it and it seems to be somewhat fixed.

> 
> I've been trying to disable as many options and lower as many values in the kernel as possible, but no shell so far 😅

**Comment by disdi** [comment]
> Yes, it runs out of memory, unfortunately. I haven't gotten a shell working.... you can get the kernel to fit in ~2.3Mb by disabling a bunch of stuff in the config. 
> 

I cannot get the Kernel Image to reduce below 4Mb. Can you share the config file which can fit it in 2.3 Mb ?

**Comment by Mr-Bossman** [comment]
@disdi if you set the init system to none it will start /bin/sh and will succeed, but for some reason panics.
https://github.com/Mr-Bossman/pi-pico2-linux/tree/test-init
