### ISSUE TITLE
flash_kernel isn't findingf the SDK

### ISSUE THREAD

**Issue by znmeb** [Mr-Bossman/pi-pico2-linux#2]
I got everything to work up to the `make flash-kernel` step. Then it fails:

```
❯ make flash-kernel
cd build && cmake ..
CMake Error at pico_sdk_import.cmake:74 (message):
  Directory '/home/znmeb/.pico-sdk/sdk/2.0.0' not found
Call Stack (most recent call first):
  CMakeLists.txt:40 (include)


-- Configuring incomplete, errors occurred!
make: *** [Makefile:10: build/Makefile] Error 1
```

I have the SDK installed at `$HOME/CLAMS_base/pico_repos/pico-sdk`.

**Comment by disdi** [comment]
Same issue

**Comment by Mr-Bossman** [comment]
> I got everything to work up to the `make flash-kernel` step. Then it fails:
> 
> ```
> ❯ make flash-kernel
> cd build && cmake ..
> CMake Error at pico_sdk_import.cmake:74 (message):
>   Directory '/home/znmeb/.pico-sdk/sdk/2.0.0' not found

This is actually an issue with the vscode plugin integration. I updated it, this should be fixed.

> Call Stack (most recent call first):
>   CMakeLists.txt:40 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> make: *** [Makefile:10: build/Makefile] Error 1
> ```
> 
> I have the SDK installed at `$HOME/CLAMS_base/pico_repos/pico-sdk`.

**Comment by shtirlic** [comment]
Try to set ENV PICO_SDK_PATH
