### ISSUE TITLE
UART doesn't work

### ISSUE THREAD

**Issue by Mr-Bossman** [Mr-Bossman/pi-pico2-linux#3]
You can only type one character in the console.

**Comment by disdi** [comment]
Pleased to kernel to boot. Wished if we could do more in init.

**Comment by Mr-Bossman** [comment]
> Pleased to kernel to boot. Wished if we could do more in init.

yeah it took a bit to figure out why uart wasnt working in userspace. im still not entirely sure why its not working. after one key is pressed. it seems that the uarts irq enable ( the one in the pl011 address space) bit is being cleared at some point. i think that when using the csr to mask the interrupt it also clears it there. I'm not sure, but i think commenting out the csr_clear in mask function in the IRQ driver should fix it if thats the case. It was 3AM when i finished the IRQ driver and tested it, so i never tested that change as i was content with the console printing something.

**Comment by cardassian** [comment]
Sparkfun pico2 arrived last week. Compilation and flashing successful. Same error symptoms as already mentioned above.
You can type in ONE character. Thus, "ls" is not possible, however one CR yields another prompt of the shell. Thus, userland alive!

**Comment by Mr-Bossman** [comment]
> Sparkfun pico2 arrived last week. Compilation and flashing successful. Same error symptoms as already mentioned above.
> You can type in ONE character. Thus, "ls" is not possible, however one CR yields another prompt of the shell. Thus, userland alive!

Yes it is unfortunate the Uart isn't working correctly. Are you planning on fixing it?

**Comment by cathiele** [comment]
>  Thus, "ls" is not possible, however one CR yields another prompt of the shell. Thus, userland alive!

"ls" and other (short) commands are possible. You just have to copy & paste them. The rx fifo can handle multipe characters. 

```
~ # cat /proc/interrupts
           CPU0
  2:       1921  RISC-V INTC   7 Edge      clint-timer
 33:          1  Simple INTC  33 Edge      uart-pl011
~ #
```

**Comment by Mr-Bossman** [comment]
> > Thus, "ls" is not possible, however one CR yields another prompt of the shell. Thus, userland alive!
> 
> "ls" and other (short) commands are possible. You just have to copy & paste them. The rx fifo can handle multipe characters.
> 
> ```
> ~ # cat /proc/interrupts
>            CPU0
>   2:       1921  RISC-V INTC   7 Edge      clint-timer
>  33:          1  Simple INTC  33 Edge      uart-pl011
> ~ #
> ```

Yes I did dee the interrupt issue. The FIFO thing is interesting.
I haven't tried it, but a possible fix is to comment out https://github.com/Mr-Bossman/pi-pico2-linux/blob/a8ce37a7f1df74e8a13487f4ee1534d9981ee86a/board/raspberrypi/raspberrypi-pico2/patches/linux/0001-Add-interrupt-controller.patch#L98

**Comment by cathiele** [comment]
I tried it but it does not change anything. I added some debug output:

```
[    3.432773] irq-simple: Unmasking interrupt 33
```

and after typing something:

```
[   10.133472] irq-simple: Masking interrupt 33
[   10.152147] irq-simple: Unmasking interrupt 33
```
so that seems to work fine.

**Comment by cathiele** [comment]
It seems that the RX-interrupt is not terminating correctly. But i am not an expert of the linux kernel irq architecture.

When i increase the priority of the UART0-Interrupt via setting the MEIPRA-CSR  via GDB from 7 to 8 :

```
set $csr3043 = 0x00800008
```

I can send another set of characters. And increasing it from 8 to 9:

```
set $csr3043 = 0x00900008
```
another set.

**Comment by cathiele** [comment]
I don't know if this is a good solution, but setting the CSR ```MEICONTEXT``` to ```0x00``` at the end of ```simple_intc_irq_handler``` in irq-simple-intc.c solves this for me:

```
csr_write(0xbe5, 0x0);
```

**Comment by Sfinx** [comment]
BTW: sending any keystroke to active USB serial port from bootloader will freeze the the kernel serial port

**Comment by Mr-Bossman** [comment]
> BTW: sending any keystroke to active USB serial port from bootloader will freeze the the kernel serial port

Oh yeah. the kernel probably panics as it gets a random interrupt it doesn't know what to do with. if u want me to fix this. make a new issue please

**Comment by Sfinx** [comment]
No no, just noticed this
